CREATE TABLE IF NOT EXISTS TIME_SERIES_INTRADAY(symbol TEXT NOT NULL, datetime TEXT NOT NULL, open REAL, high REAL, low REAL, close REAL, volume INTEGER);
CREATE TABLE IF NOT EXISTS TIME_SERIES_DAILY(symbol TEXT NOT NULL, datetime TEXT NOT NULL, open REAL, high REAL, low REAL, close REAL, volume INTEGER);
CREATE TABLE IF NOT EXISTS TIME_SERIES_DAILY_ADJUSTED(symbol TEXT NOT NULL, datetime TEXT NOT NULL, open REAL, high REAL, low REAL, close REAL, adjusted_close REAL, volume INTEGER, dividend_amount REAL, split_coefficient REAL);
CREATE TABLE IF NOT EXISTS TIME_SERIES_WEEKLY(symbol TEXT NOT NULL, datetime TEXT NOT NULL, open REAL, high REAL, low REAL, close REAL, volume INTEGER);
CREATE TABLE IF NOT EXISTS TIME_SERIES_WEEKLY_ADJUSTED(symbol TEXT NOT NULL, datetime TEXT NOT NULL, open REAL, high REAL, low REAL, close REAL, adjusted_close REAL, volume INTEGER, dividend_amount REAL);
CREATE TABLE IF NOT EXISTS TIME_SERIES_MONTHLY(symbol TEXT NOT NULL, datetime TEXT NOT NULL, open REAL, high REAL, low REAL, close REAL, volume INTEGER);
CREATE TABLE IF NOT EXISTS TIME_SERIES_MONTHLY_ADJUSTED(symbol TEXT NOT NULL, datetime TEXT NOT NULL, open REAL, high REAL, low REAL, close REAL, adjusted_close REAL, volume INTEGER, dividend_amount REAL);
CREATE TABLE IF NOT EXISTS DATA_STATUS(symbol TEXT NOT NULL, function TEXT NOT NULL, interval TEXT, DATA_STATUS datetime NUMERIC NOT NULL)